### ISSUE TITLE
nullpointer exception

### ISSUE THREAD

**Issue by RobertHeim** [chargebee/chargebee-flutter#24]
```
await Chargebee.retrieveProductIdentifers({});
```
gives
```
E/MethodChannel#chargebee_flutter(17449): Failed to handle method call
E/MethodChannel#chargebee_flutter(17449): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
E/MethodChannel#chargebee_flutter(17449): 	at com.chargebee.flutter.sdk.ChargebeeFlutterSdkPlugin.retrieveProductIdentifers(ChargebeeFlutterSdkPlugin.kt:242)
E/MethodChannel#chargebee_flutter(17449): 	at com.chargebee.flutter.sdk.ChargebeeFlutterSdkPlugin.onMethodCall(ChargebeeFlutterSdkPlugin.kt:83)
E/MethodChannel#chargebee_flutter(17449): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#chargebee_flutter(17449): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#chargebee_flutter(17449): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/MethodChannel#chargebee_flutter(17449): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#chargebee_flutter(17449): 	at android.os.Handler.handleCallback(Handler.java:873)
E/MethodChannel#chargebee_flutter(17449): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#chargebee_flutter(17449): 	at android.os.Looper.loop(Looper.java:193)
E/MethodChannel#chargebee_flutter(17449): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#chargebee_flutter(17449): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#chargebee_flutter(17449): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#chargebee_flutter(17449): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by cb-amutha** [comment]
Hi @RobertHeim, thanks for reporting the issue.
Could you please pass the queryParams like {"limit":"100"} to retrieve the products? 
**For example,**  await Chargebee.retrieveProductIdentifers({"limit":"100"});

Thanks.

**Comment by RobertHeim** [comment]
When passing the `limit`, the NPE goes away, but the method never finishs, just like the `configure` method, as reported here: https://github.com/chargebee/chargebee-flutter/issues/23
