### ISSUE TITLE
App crashes on Android: "Reply already submitted"

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-flutter#93]
This seems to happen since we upgraded to v1.0.0 of the `chargebee-flutter` sdk.

Unfortunately I wasn't able to reproduce this, I just got this from Crashlytics during production.

### Stacktrace

```log
Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at lh.c$g.a(SourceFile:1)
       at uh.k$a$a.b(SourceFile:1)
       at h4.b.f(SourceFile:1)
       at h4.b.g(SourceFile:1)
       at h4.b.b(SourceFile:1)
       at h4.b$i.onError(SourceFile:1)
       at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$2.invoke(SourceFile:2)
       at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$2.invoke(SourceFile:1)
       at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$3.invoke(SourceFile:2)
       at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$3.invoke(SourceFile:1)
       at com.chargebee.android.billingservice.BillingClientManager$createBillingClientStateListener$1.onBillingServiceDisconnected(:15)
       at c3.u.onServiceDisconnected(SourceFile:1)
       at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:2226)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2241)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
````

**Comment by ciriousjoker** [comment]
- Just found #71 again, makes more sense to continue there, sorry for creating this, I thought the other one was closed already.
